languageCode = "en-us"
title = "Holitica"
theme = "paper"
enableRobotsTXT = true

[params]
  name = "We connect software, data, design, and people"
  bio = "team@holitica.it"
  color = "linen"
  github = "vshneer"
  linkedin = "victor-shneer"
