languageCode = "en-us"
title = "Software. Data. Design. People"
theme = "paper"
enableRobotsTXT = true

[params]
  name = "Victor Shnaier. I build software"
  bio = "victor@holitica.it"
  color = "linen"
  linkedin = "victor-shneer"
