baseURL = "http://localhost/"
languageCode = "en-us"
title = "My name is Victor Shnaier"
theme = "paper"
enableRobotsTXT = true

[params]
  name = "Welcome to my blog. I build software using Java"
  bio = """Here I post Java code snippets and write about benefits of functional approach.

Contact me - I can build a product for you."""
  color = "linen"
  github = "vshneer"
  linkedin = "victor-shneer"
